### ISSUE TITLE
NaN dependency broken

### ISSUE THREAD

**Issue by jokesterfr** [santigimeno/node-pcsclite#27]
Hey,
`node-pcsclite` was working on monday with NaN __1.4.1__, today it's not working anymore with NaN __1.5.1__.
I suggest setting the exact dependency in the *package.json* ;)

**Comment by santigimeno** [comment]
@jokesterfr See this: https://github.com/santigimeno/node-pcsclite/pull/28. It builds again, but I can't test it ATM. I would appreciate if you could test it.
Thanks!

**Comment by jokesterfr** [comment]
This is much better, at least it builds ;-) I cannot try any further at the moment

**Comment by santigimeno** [comment]
Fixed in https://github.com/santigimeno/node-pcsclite/pull/28

**Comment by santigimeno** [comment]
Released in 0.3.6

**Comment by jokesterfr** [comment]
thank you !
