### ISSUE TITLE
Crash application when using into node-webkit

### ISSUE THREAD

**Issue by yeomi** [santigimeno/node-pcsclite#37]
Hello,

First of all thanks for providing this wrapper,
I am trying to use it in a node-webkit application, however app is crashing everytime node-pcsclite, 

At the moment i've been trying basic code, and even with the example you provide on the project page I am getting the following error : 

```nwjs Helper(955,0x7fff716c8180) malloc: *** error for object 0x7f8649476058: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug```

Right before getting this message, and on the first time usage, everything is working great. but then it crashs, and keep crashing until I purge computer memory.
As I say for the moment the app is just a basic try, the application is not doing anything else but testing the example code. 

Not sure what can I do to help.

Thanks

**Comment by santigimeno** [comment]
@yeomi Can you get attach a debugger and post a full backtrace of the crash?

**Comment by santigimeno** [comment]
@yeomi Can you try with the `0.4.2` version as I have fixed a crash? Thanks!

**Comment by santigimeno** [comment]
Closing due lack of feedback. Feel free to reopen if it's still an issue
