### ISSUE TITLE
npm WARN package.json pcsclite@0.4.2 license should be a valid SPDX license expression

### ISSUE THREAD

**Issue by LudovicRousseau** [santigimeno/node-pcsclite#39]
Maybe you could just reuse an existing license text like MIT.

Proposed patch:
```
+++ package.json    2015-09-13 14:22:36.000000000 +0200
@@ -30,9 +30,6 @@
       "smartcards"
     ],
     "author": "Santiago Gimeno <santiago.gimeno@gmail.com>",
-    "license": {
-        "type": "ISC",
-        "url": "https://github.com/santigimeno/node-pcsclite/blob/master/LICENSE"
-    },
+    "license": "MIT",
     "gypfile": true
 }
```

**Comment by santigimeno** [comment]
Thanks for the info. I don't know what the problem with the current format is, I'll have to look into it before making any change.

**Comment by santigimeno** [comment]
As of `npm@3.8.3` this does not seem to be an issue anymore. Feel free to reopen if you think there's anything else to be done. Thanks
