### ISSUE TITLE
Error with the buffertools package on install

### ISSUE THREAD

**Issue by noopole** [santigimeno/node-pcsclite#47]
Hello I'm trying to install pcsclite on Windows but I get an error with the node-gyp rebuild.
Do I need to install Python before?
Thank you for your answer.
Bruno
______________________________________
Here is the log from the command line.

PS C:\Windows\system32> npm install pcsclite
npm WARN engine pcsclite@0.4.4: wanted: {"node":">=0.8.0 < 4"} (current: {"node":"4.0.0","npm":"2.14.2"})"
-
> buffertools@2.1.3 install C:\Windows\system32\node_modules\pcsclite\node_modules\buffertools
> node-gyp rebuild

C:\Windows\system32\node_modules\pcsclite\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-g
yp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\system32\node_modules\pcsclite\node_modules\buffertools
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pcsclite"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

**Comment by santigimeno** [comment]
Yes, python 2.6 or 2.7 is a pre-requisite to use native addons.
BTW the WARNING regarding the node version is harmless

**Comment by noopole** [comment]
Thank you very much for this quick answer.
