### ISSUE TITLE
Client Side Javascript accessing client-connected devices

### ISSUE THREAD

**Issue by brunobertechini** [santigimeno/node-pcsclite#50]
Hi there nice project...

Is this project goal to enable client side javascript to access client-connected pcsc devices?

I mean, it runs on node.js at the server, but the javascript at local client would be able to connect to SmartCard readers connected to client computer (running browser) ?

Bruno

**Comment by santigimeno** [comment]
@brunobertechini thanks!

No it's not. How would you do that?
I don't think that's feasible. For example, in Linux, you would need to communicate with the local `pcscd` service in some way, and I don't think the browser allows to execute that kind of code.

**Comment by brunobertechini** [comment]
We currently use silverlight for client side smart cards. ..
It works but silverlight is being demised and we are looking for replacement 
Bruno


Sent from my Samsung device

-------- Original message --------

**Comment by santigimeno** [comment]
@brunobertechini I didn't know about that. Thanks for pointing that out. So you need to install a plugin in the browser to execute the PCSC code right? If that's the case, one of the problems I see: is there a standard way to call native code that works across browsers / O.S.? (I've found this for firefox: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes). In addition, this module is built on the nodejs platform, and it looks like keeping compatibility with it and the browsers like a difficult task(maybe there's a simple way I don't know of :( ).

So I don't know, I don't plan / need implementing support for this but if anyone needs it and implements it keeping the current functionality/API I'd be glad to merge it but I would not be surprised it would be easier to implement the browser plugins from scratch.

**Comment by brunobertechini** [comment]
The problem is even browser plugins are on the fight for survival these days...

I could'nt find any alternative to be able to Send APDUs to smartcards when the device is connected to client computer.

Only silverlight or a thin client application using websocket (through server requests)

Bruno

**Comment by LudovicRousseau** [comment]
The w3c is working on an API for browsers: secure element API
http://www.w3.org/wiki/System_Applications_WG:_Secure_Elements_API

Gemalto has the "sconnect" product but that is not Free Software.

**Comment by santigimeno** [comment]
It seems that there's nothing actionable here.
