### ISSUE TITLE
Example code works well for one, not at all for another

### ISSUE THREAD

**Issue by pvencill** [santigimeno/node-pcsclite#53]
Sorry if this is in the wrong place, this does not seem to be a pcscLite issue, but one with the example code for the node bindings, or perhaps my understanding of things.  I'm pretty new to APDU and smart cards in general. 

I have two different smart cards from (presumably) two vendors.  I don't know for sure because there's no indication on either card, but they're issued by two different organizations, so I'm making an assumption that they're different.  In any case, let's call them Card A and Card B.

Using the sample code provided in this module, Card A inserted into a card reader will receive the transmit buffer of [0x00,0xB0,0x00, 0x00, 0x20] and respond with its own buffer array. I haven't gotten to where I can make use of the response yet beyond printing the hex to the screen, but that's part of my learning curve and I accept it.

Card B, however, running the same code on the same host in the same card reader, responds with 'SCardTransmit error: Transaction failed. (0x80100016)'. Note that this card works fine with company-provided applications (e.g. signing & encrypting emails, etc), so it's not a faulty card. 

Any thoughts on how to proceed?

**Comment by LudovicRousseau** [comment]
Please follow https://pcsclite.alioth.debian.org/pcsclite.html#support

**Comment by pvencill** [comment]
Juice ain't worth the squeeze.  I got my code working by piping through commandline (pkcs15-tool).
