### ISSUE TITLE
electron integration

### ISSUE THREAD

**Issue by steveoriol** [santigimeno/node-pcsclite#55]
Hello,
I try to use node-pcsclite with [electron](https://github.com/atom/electron) to make a desktop application.
if I use only node-pcsclite, it's works.
but as soon I add "var pcsc = require('pcsclite');" in the main.js of the electron main file, I get this error:
`Error: Cannot find module './build/Debug/buffertools.node'`

I find this [issue](https://github.com/bnoordhuis/node-buffertools/issues/71), but I do not understand how to fix the problem, in my case it does not even work on the developement computer.
Can you help me,
I'm running Ubuntu 14.04 LTS 64

**Comment by santigimeno** [comment]
@steveoriol I've installed https://github.com/atom/electron-quick-start, installed `pcsclite`, added some `pcsclite` code to `main.js` and started the application and had no problems.
What `nodejs` version are you using? What `pcsclite` version?  Have you tried running `npm rebuild`?

**Comment by steveoriol** [comment]
Thank you santigimeno !
by running `npm rebuild`, It's working now, cool :-)
`node -v => v5.8.0` and `npm list pcsclite` => pcsclite@0.4.8 
Merci

**Comment by santigimeno** [comment]
Great! Closing it then.
