### ISSUE TITLE
Unable to build on nwjs v0.13.4 on Windows 7 x64 / Mac

### ISSUE THREAD

**Issue by jankomartin** [santigimeno/node-pcsclite#56]
Hello,
I have done some evaluation on you pcsc library and it looks perfectly suited for mine need from the functional point, but I have hit on one big issue. 

I'm unable to build your pcsclite application on Windows 7 x64/ia32 when using nwjs v0.13.4 (the latest stable version). I have been playing quite long with this topic and have found that I'm able to build it for nwjs version v0.13.0-beta7.

I'm using Visual Studio 2013

On Mac is workign eveything fine.

Working command
cd node_modules\pcsclite
nw-gyp rebuild --target=0.13.0-beta7 --arch=ia32

Error command
cd node_modules\pcsclite
nw-gyp rebuild --target=0.13.4 --arch=ia32

Error message:
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1

Please can you advice ?

Thanks a lot.

[output.txt](https://github.com/santigimeno/node-pcsclite/files/214545/output.txt)

**Comment by santigimeno** [comment]
@jankomartin what `nan` version do you have installed when building the project. If it's not `2.2.1` (the latest), can you upgrade to that one and check if it works?

**Comment by jankomartin** [comment]
Hello, 
I have checked the package.json of the nan module (locally installed package) and there it says "nan@~2.2.1". 
So according me I'm already using the latest one.

**Comment by jankomartin** [comment]
Hello, 
I have discovered that when I install the pcsclite via the 
npm install pcsclite than it creates a nested nan module with version 2.2.0 so the structure looks like:

APP\
APP\node_modules\nan (version 2.2.1)
APP\node_modules\pcsclite
APP\node_modules\pcsclite\node_modules\nan (version 2.0.0)

This dependency is mentioned in your file pcsclite\package.json (line 46)

**Comment by santigimeno** [comment]
Ok, why don't you change the `nan` dependency in `pcsclite` `package.json` to `2.2.1` and let me know how it goes? Thanks!

**Comment by santigimeno** [comment]
Or just remove the `APP\node_modules\pcsclite\node_modules\nan` folder.

**Comment by jankomartin** [comment]
Hi, 
I have removed the APP\node_modules\pcsclite\node_modules\nan and I your module compiled without any problem. So from mine point of view it looks good.

In a mean while I will use this workaround. Do you plan to fix it also in npm repository ? 

Anyway thanks for help :) and good luck.

**Comment by santigimeno** [comment]
Fixed and published in `0.4.9`. 
Thanks
