### ISSUE TITLE
Unable to build on Mac OS X El Capitan

### ISSUE THREAD

**Issue by guoway** [santigimeno/node-pcsclite#60]
Environment:
OS : Mac OS X El Capitan
Node.js version : v6.3.0
pcsclite version : 0.4.9

Situation : 
Following is the output when I was installing pcsclite.
`kens-MacBook-Pro:node-pcsclite-master Ken$ npm install`
`npm WARN package.json pcsclite@0.4.9 license should be a valid SPDX license expression`
`> pcsclite@0.4.9 install /Users/ken/Documents/workspace/workspace_nodejs/node-pcsclite-master`
`> node-gyp rebuild`

`  CXX(target) Release/obj.target/pcsclite/src/addon.o`
`  CXX(target) Release/obj.target/pcsclite/src/pcsclite.o`
`../src/pcsclite.cpp:286:20: warning: comparison of integers of different signs: 'LONG' (aka 'int') and 'unsigned int' [-Wsign-compare]`
`        if (result == SCARD_E_INSUFFICIENT_BUFFER) {`
`            ~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~`
`1 warning generated.`
`  CXX(target) Release/obj.target/pcsclite/src/cardreader.o`
`  SOLINK_MODULE(target) Release/pcsclite.node`

Can you help to solve it ? 
Thank you ~

**Comment by santigimeno** [comment]
@guoway are you sure it's failing, from the logs it seems like a warning and not an error. (of course the warning should be fixed)

**Comment by guoway** [comment]
Sorry about that, I'm new to node.js, so cannot figure it clearly, now I know that's just a warning but error, sorry to bother you ~

**Comment by santigimeno** [comment]
No problem. Thanks for the report though, I'll try to fix it asap
