### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by kainoffke** [santigimeno/node-pcsclite#63]
Hi,

We will start a new project using your really nice library. Since we are going to use Typescript as our language of choice I sat down and wrote the typings. I asked myself if you would like to incorporate these typings in your project or if you would rather like to see them in the _DefinitelyTyped_-repository. 

They may be not yet perfect but they work ;)

Just let me know if I should create a PR.

**Comment by santigimeno** [comment]
@kainoffke, hi! tbh I don't know anything about Typescript. What do you think it's the best option? any pros / cons doing one way or the other? Thanks!

**Comment by kainoffke** [comment]
The only pro I can think of, is that people using your library in a Typescript based project can access the typings without further dependencies.

A con might be, that hosting the typings inside your repo could imply that you are the one keeping them up to date. Which is actually a big con if you don't really care about Typescript. In that case I would rather try to get them published at DefinitelyTyped.

You could then just link to the typings, if you'd like to do so.

**Comment by santigimeno** [comment]
@kainoffke thanks for the thorough answer and sorry for the delay, somehow I missed your response. From what you say, probably the best option would be the 2nd one: you publish them to `DefinitelyTyped` and the we could add a link to the typings in the `README.md`. (maybe you could send a PR for that :) ). Does that sound good? Thanks!

**Comment by jorispz** [comment]
Hi @kainoffke, I recently moved my pcsclite-based project over to TypeScript, and I would love to reuse the type definitions you have created. Are they available anywhere?

**Comment by jorispz** [comment]
I am using the same fork, so this is perfect, thanks!

Op vr 17 aug. 2018 07:20 schreef kainoffke <notifications@github.com>:

**Comment by lewixlabs** [comment]
Yes thank you!
I used the same fork to build my TypeScript wrapper, if anybody is interested is here:
https://github.com/lewixlabs/TsCard
👍
