### ISSUE TITLE
How do you list all readers, including internal ones?

### ISSUE THREAD

**Issue by all-hack** [santigimeno/node-pcsclite#77]
E.g. readers that are "never inserted" and therefore are not detected by `on("reader")`.

**Comment by martinpaljak** [comment]
in PC/SC terms such readers do not exist. A reader event is emitted during initial enumeration, thus you get a list of all usable smart card readers.

**Comment by all-hack** [comment]
Thank you - to that effect, we ended up exposing `readers` in `lib/pcsclite.js:34`, as by the time we can attach a listener to `on(“reader”)` the initial reader(s) have already been enumerated. PR may follow soon.

**Comment by santigimeno** [comment]
https://github.com/santigimeno/node-pcsclite/pull/78 already landed
