### ISSUE TITLE
electron and Ionic integration

### ISSUE THREAD

**Issue by Rokia88** [santigimeno/node-pcsclite#80]
hello,

I have an electron application built upon Ionic framework. 
I need to use pcsclite to read smart cards, but when I run 'npm run build' or 'ionic build' I got this error 
Error: ./node_modules/buffertools/buffertools.js
Module not found: Error: Can't resolve './build/Debug/buffertools.node'
My node version is v9.4.0 and pcsclite version. is 0.6.0
when I run the example in the nod-pcsclite project. I do not have any problem.

Thanks in advance for your help

**Comment by prophet1996** [comment]
Same issue
![screenelectron](https://user-images.githubusercontent.com/16836510/37352652-c254eb3e-2703-11e8-8fdf-90eee38a07c2.png)

**Comment by santigimeno** [comment]
This should be fixed in version `v1.0.0`.
