### ISSUE TITLE
Can't compile it - Buffertools package went unmantained

### ISSUE THREAD

**Issue by glococo** [santigimeno/node-pcsclite#88]
Hi,

Can't compile it.
Ubuntu 19.04 - Node 12.1 - Node-gyp 3.8

Buffertools went unmantained, 
https://github.com/bnoordhuis/node-buffertools/issues/93#issuecomment-439425261

thanks

**Comment by cklee75** [comment]
Same issue for 
Windows 10
Node v12.3.1
Node-gyp v3.8.0

Thanks.

**Comment by santigimeno** [comment]
This should be fixed in version `v1.0.0`.
